### ISSUE TITLE
✅  本番環境でログインできない

### ISSUE THREAD

**Issue by kira-0521** [kira-0521/todo-app-ai#27]
- DBのUserテーブルにはサインアップしたデータは格納されている
- 以下のように`emailVerified`がnull

<img width="437" alt="スクリーンショット 2024-03-06 8 46 15" src="https://github.com/kira-0521/todo-app-ai/assets/67964748/965385d9-f22e-44fe-9043-240bcc2e247e">

**Comment by kira-0521** [comment]
Vercelのログを確認すると `column is too long` が原因？

```
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error 
Invalid `prisma.account.create()` invocation:


The provided value for the column is too long for the column's type. Column: for PrismaClientKnownRequestError: 
Invalid `prisma.account.create()` invocation:


The provided value for the column is too long for the column's type. Column: for
    at _n.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6854)
    at _n.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6188)
    at _n.request (/var/task/node_modules/@prisma/client/runtime/library.js:123:5896)
    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:128:10871) {
  name: 'LinkAccountError',
  code: 'P2000'
}
```

**Comment by kira-0521** [comment]
id_tokenの方がvercharだとダメらしい
TEXT型にする必要があるようで、ローカルでは対応していたが、PlanetScalに適用していなかったので発生したエラー

https://github.com/nextauthjs/next-auth/issues/4734

**Comment by kira-0521** [comment]
### 本番環境DBのScheme変更してもダメそうだから一回データ消したほうがいいかも

![スクリーンショット 2024-03-06 9 52 53](https://github.com/kira-0521/todo-app-ai/assets/67964748/d5263e1b-e85f-4cc3-9102-229d9d15d533)

**Comment by kira-0521** [comment]
SocialConnectionsからプロバイダーを選択可能
Github追加

**https://manage.auth0.com/dashboard/jp/todo-app-ai/connections/social**

🤔 またGithubからログインするとログインができたが、DBにデータがない

**Comment by kira-0521** [comment]
Prisma log：DBのUserが変更されていた

```sh
Invalid `prisma.account.findUnique()` invocation:
```

**Comment by kira-0521** [comment]
やはりDBにアクセスできないのが問題らしい。
UsernameとPasswordを改めて確認。

-> 再度PlanetScaleでpassword発行してvercelのenvにセット
-> ✅ いけた！！！
-> ✅ NextAuthのSessionテーブルのデータは一時的なもので、ユーザーがログアウトすると消える
